# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34fe926e7dbb812c459aff45058d0125c7e4df1e205616e0766397c08c8bd30c7098b7ff960b9e48a5b50c988ad7b65518c8935f3be336f2b1e376a63e543cd3

test:
  secret_key_base: c43478b4dc1a65da9e2d52cb48e7113186fa7b2e2a2a9da49f8e916abc600d1b2a4924335dd108ff113f0aa5373b8df157f2892be5dfe24b1970001e7b6f569b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
